### ISSUE TITLE
Bug with collision

### ISSUE THREAD

**Issue by ooCristalloo** [PowerNukkitX/PowerNukkitX#1123] opened 2023-04-03 21:32 UTC
I found a bug related to AI and collisions, if you spawn several mobs nearby, they will prevent each other from moving due to collision, if you push them away from each other, they start walking, but again they can get stuck in each other's collision

**Comment by CoolLoong** [comment] 2023-04-04 00:14
Provide reproducible code

**Comment by ooCristalloo** [comment] 2023-04-04 04:03
> Provide reproducible code

Yes of course, here is the Entity class:
https://pastebin.com/dikbjGp1
Here is my sensor:
https://pastebin.com/T66z9nB4

**Comment by CoolLoong** [comment] 2023-04-04 09:18
record
```java
public class Minotavr extends EntityMob implements CustomEntity, EntityWalkable, EntityInventoryHolder {

    public final static CustomEntityDefinition def = CustomEntityDefinition.builder().identifier("crbe:minotavr").summonable(true).spawnEgg(false).build();

    public Minotavr(FullChunk chunk, CompoundTag nbt) {
        super(chunk, nbt);
    }

    public IBehaviorGroup requireBehaviorGroup() {
        return new BehaviorGroup(this.tickSpread,
                Set.of(),
                Set.of(new Behavior(new MeleeAttackExecutor(CoreMemoryTypes.ATTACK_TARGET, 0.20F, 30, true, 10),
                        this.all(new MemoryCheckNotEmptyEvaluator(CoreMemoryTypes.ATTACK_TARGET), (entity) -> {
                            if (entity.getMemoryStorage().notEmpty(CoreMemoryTypes.ATTACK_TARGET)) {
                                Object playerObj = entity.getMemoryStorage().get(CoreMemoryTypes.ATTACK_TARGET);
                                if (playerObj instanceof Player player) {
                                    if (!player.isOnline()) {
                                        return false;
                                    }
                                }
                            }
                            return true;
                        }), 2, 1)), Set.of(new Sensor()), Set.of(new WalkController(), new LookController(true, true)), new SimpleFlatAStarRouteFinder(new WalkingPosEvaluator(), this), this);
    }

    public void displayHealthBar() {
        double health = this.getHealth();
        double maxHealth = this.getMaxHealth();

        int barLength = 10;
        int barPercent = (int) Math.round(health / maxHealth * 100);
        int barFillLength = Math.round(barLength * ((float) barPercent / 100));

        String healthBar = "§a|".repeat(Math.max(0, barFillLength)) + "§c|".repeat(Math.max(0, barLength - barFillLength));

        this.setNameTag(healthBar);
        this.setNameTagAlwaysVisible(true);
    }

    @Override
    protected void initEntity() {
        this.diffHandDamage = new float[]{0F};
        this.setMaxHealth((int) MobsController.getHealthMob(MobsInterface.MINOTAVR));
        this.setHealth((int) MobsController.getHealthMob(MobsInterface.MINOTAVR));
        super.initEntity();
    }

    @PowerNukkitXOnly
    @Override
    public boolean onUpdate(int currentTick) {
        this.displayHealthBar();
        this.diffHandDamage = new float[]{(float) MobsController.getDamageMob(MobsInterface.MINOTAVR)};
        Player target = Server.getInstance().getPlayer(this.namedTag.getString("Target"));

        if (target == null || !Objects.equals(target.getLevel().getFolderName(), "world")) {
            this.despawnFromAll();
            if (this.isValid() || this.isAlive()) {
                this.kill();
            }
            return super.entityBaseTick(currentTick);
        }
        return super.onUpdate(currentTick);
    }

    @Since("1.19.60-r1")
    @Override
    public double getFloatingForceFactor() {
        return 0.7;
    }

    @Override
    public boolean attack(EntityDamageEvent source) {
        var result = super.attack(source);
        if (source instanceof EntityDamageByEntityEvent entityDamageByEntityEvent) {
            getMemoryStorage().put(CoreMemoryTypes.ATTACK_TARGET, entityDamageByEntityEvent.getDamager());
        }
        return result;
    }

    @Override
    public void kill() {
        super.kill();
        Player target = Server.getInstance().getPlayer(this.namedTag.getString("Target"));
        if (!(target instanceof GamePlayer)) return;
        if (target.isOnline()) {
            if (((GamePlayer) target).getTeamModel() != null) {
                ((GamePlayer) target).getTeamModel().increase();
            } else {
                if (this.isAlive()) {
                    this.despawnFromAll();
                }
            }
        } else {
            this.despawnFromAll();
        }
    }


    public float getWidth() {
        return 0.9F;
    }

    public float getHeight() {
        return 2.1F;
    }

    public int getNetworkId() {
        return -1;
    }

    public CustomEntityDefinition getDefinition() {
        return def;
    }

    public String getOriginalName() {
        return "Minotavr";
    }
}
```
```java
public class Sensor implements ISensor {
 
    public Sensor() {
    }
 
    @Override
    public void sense(EntityIntelligent entityIntelligent) {
        if(entityIntelligent.getMemoryStorage().isEmpty(CoreMemoryTypes.ATTACK_TARGET)) {
            Player player = Server.getInstance().getPlayer(entityIntelligent.namedTag.getString("Target"));
            entityIntelligent.getMemoryStorage().put(CoreMemoryTypes.ATTACK_TARGET, player);
        }
    }
}
```

**Comment by CoolLoong** [comment] 2023-04-04 09:20
Provide the collision box aabb you set up

**Comment by CoolLoong** [comment] 2023-04-04 09:59
Can you provide a video? I have set up the same Width and Height as your code on the zombie.The collision of entities is normal, but the only lack is that entity pathfinding does not calculate the collision box of other entities.This has never been implement

**Comment by CoolLoong** [comment] 2023-04-04 10:12
If your physical collision box is large and the paths overlap,It's easy to get stuck due to collisions with each other. I think the optimization method is 
1. Override the `handleCollideMovement` method, customize your own logic for handling collisions, and add motion to entities when they collide to move them away
2. Optimize physical paths and avoid overlapping paths as much as possible. 
3. Reduce physical collision box ,even close it

**Comment by ooCristalloo** [comment] 2023-04-06 13:04
https://pastebin.com/4bzfqBrp
this code solved all problems at once

**Closed** 2023-04-11 11:39 UTC
Labels: bug | 漏洞, Need Extra Information | 需要更多信息
